### ISSUE TITLE
Add Readme to PyPI

### ISSUE THREAD

**Issue by nrempel** [InstantDomain/instant-segment#13]
Right now PyPI is pretty bare: https://pypi.org/project/instant-segment/

I'm not very familiar with how we're building for python but we could copy the README into the build directory before publishing to include that in PyPI

**Comment by djc** [comment]
Not quite sure how this is supposed to work, filed an issue: https://github.com/PyO3/maturin/issues/552.

**Comment by djc** [comment]
89c232e3afe8613fdb0f7dce63048f9b8b5e6a06 seems to have done the trick.
