### ISSUE TITLE
Support numbers?

### ISSUE THREAD

**Issue by aschiavon91** [InstantDomain/instant-segment#30]
Hello! Firstly, thanks for all effort and time invested in this project.
I'm currently planning to use it as part of a fraud detection system, and it has been very promising, but I will need to support the detection of word permutations like `ch00s3` or `sp41n`. I know that allowing numbers sounds a little weird to a word segmentation algorithm, but do you guys see any problem in include this?

**Comment by djc** [comment]
Happy that our project is of use to you! Can you say more about your expected behavior vs today's actual behavior? Do you mean to just change the code so that it would allow numbers (presumably in `Ascii::new()`)?

**Comment by aschiavon91** [comment]
Of course, the actual behavior of the `Ascii:new` function, enforces that all chars of string return true when calling 'is_ascii_lowercase()' function, so strings with any numbers on it, will return `Err(InvalidCharacter)`.
The expected behavior that I desire is this `Asciis::new` call do not return `Err(InvalidCharacter)` if used with a string with some number on it. Ex: `cheet0s`.
I already made this change in my fork ([diff](https://github.com/InstantDomain/instant-segment/compare/main...aschiavon91:instant-segment:main)), I just want to be sure that does not cause any undesired behavior, before opening the PR 😄

**Comment by djc** [comment]
A change like that seems very reasonable, please submit a PR. Style nit: I don't like multi-line `match` scrutinees, so perhaps you can bind `let mut iter = s.bytes().iter().all(..);` and then `match iter { .. }` instead.

**Comment by nrempel** [comment]
Closed by #31. Thanks!
